import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import SessionProvider from "./SessionProvider";
import SessionProvider from "./SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/authOptions";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UCSC Forum",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-200`}>
        <SessionProvider>
          <Navbar session={session}/>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
